# Numpy notes

### First thing to start with is to install the numpy library using command " pip install numpy " in your cmd

###  Or you can execute the command " ! pip install numpy " in Jupyter notebook :

In [ ]:
! pip install numpy

<br>

### Importing the numpy library :

In [15]:
import numpy as np

# Note : "np" is just a name. you can import the library as whatever you want

### Initializing array :

In [47]:
# One dimentional array 

a = np.array([1,2,3])
print (a)

[1 2 3]


In [20]:
# two dimentional array 

b = np.array([[9.0 , 8.0,7.0],[6.0,5.0,4.0]])
print (b)

[[9. 8. 7.]
 [6. 5. 4.]]


### Get the dimention of the array:

In [54]:
# you can get the dimention of an array using "ndim"

'''

here the array a is one dimentional array while array b is two dimentional array

'''

print (a.ndim)
print (b.ndim)

1
2


### Get shape of the array [r , c]

In [35]:
# you can get the shape of an array using "shape"
'''
the array a has 1 row and 3 columns  while array b has 2 rows and 3 columns 
'''
print (a.shape)
print (b.shape)

(3,)
(2, 3)


### Get data type of of elements in array

In [48]:
## you can get the type of an array using "dtype"

print (a.dtype)

int32


### To change the data type of an array

In [45]:
## you can change the type of an array using "astype"

a = a.astype('float32')

print (a.dtype)

float32


### Get size of an array 

In [53]:
## you can get the size of an array using "size"

print (a.size)
print (b.size)

3
6


### Accessing a specific element / row / column

In [65]:
a = np.array([[1,2,3,4,5,6,7] , [8,9,10,11,12,13,14]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


#### To get a specific row

In [68]:
a[0 , :]

# This line of code accessing row number 0 and prints every element in this row

array([1, 2, 3, 4, 5, 6, 7])

#### To get a specific column

In [70]:
a[ : , 2]

# This line of code accessing the column number 2 in every row in the array

array([ 3, 10])

#### More proffessional access [startindex: endindex: stepsize]

In [72]:
a[0 , 1:6:2]

# This line of code accessing row number 0 and prints from column number 1 to column number 6 with step size 2

array([2, 4, 6])

#### To change element in the array

In [75]:
a[1 , 5] = 20
# This line of code accessing the element in the row 1 and column 5 which is "13" and change it to 20
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


#### To change elements in a specific columns in every row

In [76]:
a[: , 2] = 5
# This line of code changing the value in coulmn number 2 in every row in the array to 5
print (a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


<br>

### 3-dimentional array example

In [78]:
a = np.array([ [[1,2] , [3,4]] , [[5,6] , [7,8]] ])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Get a specific element from 3D array 

In [79]:
#for example if you want to access number 4 in the previous array
a[0,1,1]

4

<Br>

## Initializing different types of array

#### The all zeros matrix

In [90]:
print(np.zeros(5))

'''
this function initializes an array of zeros with the a size that you pass within

you can also initialize the array with multi dimention as follows:
'''
print("\n")

print (np.zeros((2,3)))


[0. 0. 0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]]


#### The all ones matrix

In [96]:
'''
in the same way you can initialize an array of ones by using function "ones()"
'''
np.ones((2,2,2) , 'int16')

#Note the second parameter "int16" to change the type of the elements in the array as we change it with "astype" function before

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

#### Initialize array with any other number

In [98]:
'''
simply we use the function "full()" which takes 2 parameters:
 1-The first parameter is the shape of the array.
 2- The second parameter is the number that you want to fill the array with
'''
np.full((2,2) , 99)

#That means to initialize an array 2x2 and fill it with number 99

array([[99, 99],
       [99, 99]])