### Numpy indexing and slicing
##### Author : Rania Mustafa

### Indexing
#### One-dimensional Array
#### 1- import numpy library 
#### 2- set an numpy array 

In [3]:
import numpy as np

a = np.array([1,5,3,9])
a

array([1, 5, 3, 9])

### arrays are zero indexed.

In [7]:
a[0]

1

In [17]:
a[3]

9

In [18]:
a[3] + a[0]   

10

In [19]:
a[3]/a[1]

1.8

In [20]:
a[3] / a[0] + a[1]*a[2]

24.0

### you can slice using Index
### [index1 : index2]  -----> it will take the numbers frome index1 to index2-1

In [22]:
a[0:3]

array([1, 5, 3])

#### slicing with intervals   
##### [index1 :: index2] -----> it takes the numbers from index1 then it takes every third element of the array till the end. 

In [26]:
arr2= np.array([1,2,3,4,5,6,7,8,9])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr2[0::3]

array([1, 4, 7])

#### Omitting Indices "it is useful if you want to look at the first few rows of data frame or the first few last rows "
#### array[ :index] ------> it starts from the beginning till index-1 " it could be written as [ 0: index]"

#### array[ index: ] ------> it starts from the index till the end of the array " it could be written as [ index: 0]"
#### array [ : ] ------> it will output till the end


In [33]:
#grab first three elements
arr2[:3]

array([1, 2, 3])

In [34]:
arr2[3:]

array([4, 5, 6, 7, 8, 9])

In [36]:
arr2[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr2[0:3]

array([1, 2, 3])

### negative indices work also ,  gets the values from backwards
####             -8,-7,-6,-5,-4,-3,-2,-1 
####              0  1  2 3  4  5  6  7

In [5]:
import numpy as np

arr2= np.array([1,2,3,-5,-4,-3,-2,-1])

arr2[0:-5]

array([1, 2, 3])

In [ ]:
arr2[-3:7]

### start with 0 and add 4 each time

In [9]:
arr2[::4]   # Or [0::4]

array([ 1, -4])

### Multi-dimensional array 

In [11]:
import numpy as np
D2 = np.array([[1,2,3,4] ,[5,6,7,8],[9,10,11,12]])
D2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### to access any element ----> array name [row , column] " Just a reminder, arrays are zero indexed"


In [14]:
D2 = np.array([[1,2,3,4] ,[5,6,7,8],[9,10,11,12]])
D2[1,1]

6

### setting elements in two-dimentional array 
### array name [row , column] = new value

In [16]:
D2[1,1]= 10
D2

array([[ 1,  2,  3,  4],
       [ 5, 10,  7,  8],
       [ 9, 10, 11, 12]])

## if you didn't mention the column , the new value will be setted to the whole row   


In [17]:
D2[1] = 3
D2

array([[ 1,  2,  3,  4],
       [ 3,  3,  3,  3],
       [ 9, 10, 11, 12]])

In [19]:
D2[2][3] #oR D2[2,3]

12

In [20]:
D2[2,3]

12

## D2 [index1 : index2 , column] --------> starts frome index1 till index2-1 and output the numbers in the column

In [22]:
D2 [0:3 , 1]

array([ 2,  3, 10])

In [23]:
D2 [0:1 , 2]

array([3])

### D2[rowIndx1 : rowIndx2 , ColumnIndx1 : ColumnIndex2] -----> starts frome rowIndx1 till rowIndx2 then goes to ColumnIndx2.

In [25]:
D2[2:3 , 2:3]

array([[11]])

### [ index1 :: index2] ------>it starts with the row of index1 then it takes every "index2" column of the array till the end

In [29]:
D2[0::3]

array([[1, 2, 3, 4]])

In [26]:
D2[0::1]

array([[ 1,  2,  3,  4],
       [ 3,  3,  3,  3],
       [ 9, 10, 11, 12]])

## More Examples :

In [ ]:
D2 = np.array([[1,2,3,4] ,[5,6,7,8],[9,10,11,12]])

In [32]:
#array([[ 1,  2,  3,  4],
#       [ 5,  6,  7,  8],
#       [ 9, 10, 11, 12]])
    
D2[2::2 , 1::2]

array([[10, 12]])

In [33]:
#array([[ 1,  2,  3,  4],
#       [ 5,  6,  7,  8],
#       [ 9, 10, 11, 12]])

D2[0::1 , 0::1]

array([[ 1,  2,  3,  4],
       [ 3,  3,  3,  3],
       [ 9, 10, 11, 12]])

### ":" means selecting all the indexes

In [29]:
D2[: , 0::2]  # Here ":" is selecting all the rows

array([[ 1,  3],
       [ 3,  3],
       [ 9, 11]])

##### ValueError , slice step cannot be zero

In [30]:
D2[: , 2::0] 

ValueError: slice step cannot be zero